# Name and metadata of your task
task_name: 'Koii Health Monitor'
author: 'en0c <Lucas Jovanovich>'
description: 'This task helps the illusaq team retrieve and store data about the Koii Network found at https://koii.illusaq.com'
repositoryUrl: 'https://github.com/en0c-026/koii-health-monitor-task'
imageUrl: 'imageUrl'


# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: "IPFS"

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: ""
# OPTIONAL only Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: ""
# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 4000

audit_window: 250
submission_window: 250

# Amounts in KOII

minimum_stake_amount: 2

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10

bounty_amount_per_round: 0.1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: TASK_VARIABLE
    value: SECRET_WEB3_STORAGE_KEY
    description: 'Used to upload data to IPFS - get 1GB for free https://web3.storage'
  - type: TASK_VARIABLE
    value: SECRET_GEO2IP_ACCOUNT
    description: 'Used to geolocalization service - sign up for free https://www.maxmind.com/en/geolite2/signup'
  - type: TASK_VARIABLE
    value: SECRET_GEO2IP_KEY
    description: 'Used to geolocalization service - sign up for free https://www.maxmind.com/en/geolite2/signup'
  - type: TASK_VARIABLE
    value: GEO2IP_URL
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "5 GB"

# OPTIONAL variables below 

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: ""

